---

- name: initialize control node / repo
  hosts: localhost
  connection: local
  tasks:

  - name: init hosts
    copy:
      dest: "{{ playbook_dir }}/hosts"
      content: |
        [servers]
        node-1 ip=
        node-2 ip=
      mode: 0664
  
  - name: init vars/
    file:
      path: "{{ playbook_dir }}/vars"
      state: directory
      mode: 0775

  - name: init vars/env.yml
    copy:
      dest: "{{ playbook_dir }}/vars/env.yml"
      content: |
        ---

        K3S_TOKEN: "sup3rS3cr177ok3N"
        DNS_NAME: "rancher.home"
      mode: 0664

  - debug:
      msg: "!! Don't forget to update the hosts / env files. Only run this once. !!"
