---
- name: provision HA k3s cluster
  hosts: all
  user: mogn
  become: True
  vars:
    ETCD_DOWNLOAD_URL: https://storage.googleapis.com/etcd
    ETCD_VERSION: 3.5.0
  roles:
    - common
    - etcd
    # - k3s
    # - rancher-rke
