---

- name: common tasks
  hosts: all
  user: mogn
  become: True
  roles:
    - common

- name: provision cluster servers
  hosts: servers
  user: mogn
  become: True
  vars:
    ETCD_DOWNLOAD_URL: https://storage.googleapis.com/etcd
    ETCD_VERSION: 3.5.0
    K3S_VERSION: v1.21.2+k3s1
  vars_files:
    - vars/secrets.yml
  roles:
    - etcd
    - k3s-server
    # - rke-server

- name: provision cluster agents
  hosts: agents
  user: mogn
  become: True
  vars_files:
    - vars/secrets.yml
  roles:
    - k3s-agent
    # - rke-agent

- import_playbook: post.yml
  when: nopost is undefined or nopost == False
