---

- name: common tasks
  hosts: all
  user: mogn
  become: True
  roles:
    - common

# - name: provision external load balancers
#   hosts: load-balancers
#   user: mogn
#   become: True
#   roles:
#     - load-balancer

- name: provision cluster servers for etcd and k3s
  hosts: servers
  user: mogn
  become: True
  vars:
    ETCD_DOWNLOAD_URL: https://storage.googleapis.com/etcd
    ETCD_VERSION: 3.5.0
    K3S_VERSION: v1.21.2+k3s1
  vars_files:
    - vars/secrets.yml
  roles:
    - etcd
    - k3s-server

- name: provision cluster agents for etcd and k3s
  hosts: agents
  user: mogn
  become: True
  vars_files:
    - vars/secrets.yml
  roles:
    - k3s-agent
  
- import_playbook: kubectl.yml
  when: nokubectl is undefined or nokubectl == False

- name: provision cluster servers for rancher
  hosts: servers
  user: mogn
  become: True
  vars:
    CERT_MANAGER_VERSION: v1.0.4
    RANCHER_VERSION: 2.5.8
    DNS_NAME: rancher.mogn.co
  roles:
    - rancher
