---

- name: Common
  hosts: all
  user: mogn
  become: True
  roles:
    - common

- name: Servers | Provision (etcd + k3s)
  hosts: servers
  user: mogn
  become: True
  vars:
    ETCD_DOWNLOAD_URL: https://storage.googleapis.com/etcd
    ETCD_VERSION: 3.5.0
    K3S_VERSION: v1.21.2+k3s1
  vars_files:
    - vars/secrets.yml
  roles:
    - etcd
    - k3s-server

- name: Worker / Agent | Provision (k3s)
  hosts: agents
  user: mogn
  become: True
  vars_files:
    - vars/secrets.yml
  roles:
    - k3s-agent
  
- import_playbook: kubectl.yml
  when: nokubectl is undefined or nokubectl == False

- name: Servers | Provision (rancher)
  hosts: servers
  user: mogn
  become: True
  vars:
    CERT_MANAGER_VERSION: v1.0.4
    RANCHER_VERSION: 2.5.8
    DNS_NAME: rancher.mogn.co
  roles:
    - rancher

- name: Load Balancers | Provision (nginx)
  hosts: loadbalancers
  user: mogn
  become: True
  vars:
    DNS_NAME: rancher.mogn.co
  roles:
    - load-balancer
