---

# - name: Common
#   hosts: all
#   become: True
#   roles:
#     - common

# - name: Server | Provision
#   hosts: servers
#   become: True
#   vars:
#     CERT_MANAGER_VERSION: v1.0.4
#     ETCD_DOWNLOAD_URL: https://storage.googleapis.com/etcd
#     ETCD_VERSION: 3.5.0
#     K3S_VERSION: v1.21.2+k3s1
#     RANCHER_VERSION: 2.5.8
#   vars_files:
#     - vars/env.yml
#   roles:
#     - server

# - name: Load Balancer | Provision
#   hosts: loadbalancers
#   gather_facts: False
#   become: True
#   vars_files:
#     - vars/env.yml
#   roles:
#     - load-balancer

# - name: Agent | Provision
#   hosts: agents
#   become: True
#   vars_files:
#     - vars/env.yml
#   roles:
#     - agent
  
# - import_playbook: kubectl.yml
#   when: nokubectl is undefined or nokubectl == False

- name: Finished!
  hosts: 127.0.0.1
  vars:
    SERVER_ENDPOINT: "{{ groups['loadbalancers'][0] is defined and hostvars[groups['loadbalancers'][0]].ip or hostvars[groups['servers'][0]].ip }}"
  vars_files:
    - vars/env.yml
  tasks:

    - debug:
        msg: "!! Done. Create a DNS record or /etc/hosts entry for the load balancer / server ({{ SERVER_ENDPOINT }} -> {{ DNS_NAME }}), then browse to {{ DNS_NAME }} to finish Rancher configuration. Don't forget to source ~/.profile for kubectl access !!"
