---

- name: etcd | cleanup tar
  file:
    path: /tmp/etcd-v{{ ETCD_VERSION }}-linux-amd64.tar.gz
    state: absent
  listen: cleanup-etcd-install

- name: etcd | cleanup tmp
  file:
    path: /tmp/etcd
    state: absent
  listen: cleanup-etcd-install

- name: etcd | restore perms on server key file
  file:
    path: "{{ playbook_dir }}/certs/{{ inventory_hostname }}-key.pem"
    owner: root
    group: root
    mode: 0600
  delegate_to: localhost
  listen: cleanup-etcd-certs

- name: systemctl | daemon-reload
  command: systemctl daemon-reload
  listen: systemctl-daemon-reload
