---

# => install

- name: nginx | install
  package: 
    name: nginx
    state: present

# => copy configuration

- name: nginx | nginx.conf
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: reload-nginx

# force reload handler to fire now
- meta: flush_handlers
