---

# => configure

- name: etcd | create list of nodes to be added into the cluster
  set_fact: etcd_nodelist={%for host in groups['servers']%}{{hostvars[host].inventory_hostname}}=https://{{hostvars[host].ip}}:2380{% if not loop.last %},{% endif %}{% endfor %}

- name: etcd | create etcd.conf on node
  template:
    src: templates/etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    owner: root
    group: root
    mode: 0644

- name: etcd | create service
  template: 
    src: templates/etcd.service.j2 
    dest: /lib/systemd/system/etcd.service 
    mode: 0644
  notify: systemctl-daemon-reload

# forces the handler (systemctl-daemon-reload) to run immediately
# instead of at the end of the play
- meta: flush_handlers

- name: etcd | enable / start service
  service: name=etcd.service state=started enabled=yes
