---

# => checks

- name: check etcd version
  shell: "etcd --version | grep {{ ETCD_VERSION }}"
  register: etcd_version_match
  changed_when: False
  ignore_errors: yes

# => install (if it isn't installed or our version doesn't match)

- import_tasks: etcd-install.yml
  when: etcd_version_match.rc != 0

# => configuring certificates

- import_tasks: certs.yml

# => configuring and enabling

- import_tasks: etcd.yml

# => verifying etcd service health

- name: etcd | check service health
  shell: "curl --cacert /etc/etcd/etcd-ca.crt --cert /etc/etcd/server.crt --key /etc/etcd/server.key https://{{ hostvars[inventory_hostname].ip }}:2379/health"
  register: etcd_health_cmd
  changed_when: False

- set_fact: 
    etcd: "{{ etcd_health_cmd.stdout | from_json }}"

- block:
    - name: "etcd | stop play if service is unhealthy"
      debug:
        msg: "!! etcd is unhealthy, manual intervention required. Ending play !!"

    - meta: end_play
  when: etcd.health == 'false'
