---

# => checks

- name: rancher | prerequisite check | rancher installed
  shell: kubectl -n cattle-system rollout status deploy/rancher | grep successfully
  changed_when: False
  ignore_errors: yes
  register: rancher_installed
  delegate_to: localhost

# => prerequisites

- name: rancher | add rancher helm repo
  shell: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable && helm repo update
  changed_when: False
  delegate_to: localhost

- name: rancher | create cattle-system namespace
  command: kubectl create namespace cattle-system
  changed_when: False
  ignore_errors: yes
  delegate_to: localhost

# => install and configure cert-manager

- import_tasks: rancher-certs.yml

# => install

- name: rancher | install
  shell: "helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname={{ DNS_NAME }} --version {{ RANCHER_VERSION }}"
  when: rancher_installed.rc != 0
  ignore_errors: yes
  delegate_to: localhost

- name: rancher | wait for rollout to complete
  shell: "kubectl -n cattle-system rollout status deploy/rancher"
  changed_when: False
  register: rancher
  until:      
    - '" successfully "  in rancher.stdout'      
  retries: 12
  delay: 10
  when: rancher_installed.rc != 0
  delegate_to: localhost
