---

# => checks

- name: rancher | certs | prerequisite check | namespace
  shell: kubectl get namespaces | grep cert-manager
  changed_when: False
  ignore_errors: yes
  register: cert_manager_namespace
  delegate_to: localhost

# => configure

- name: rancher | certs | CustomResourceDefinition
  shell: "kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/{{ CERT_MANAGER_VERSION }}/cert-manager.crds.yaml"
  # when: cert_manager_namespace.rc != 0
  delegate_to: localhost

- name: rancher | certs | add jetstack helm repo
  shell: helm repo add jetstack https://charts.jetstack.io && helm repo update
  changed_when: False
  delegate_to: localhost

- name: rancher | certs | create cert-manager namespace
  command: kubectl create namespace cert-manager
  # when: cert_manager_namespace.rc != 0
  delegate_to: localhost

# => install

- name: rancher | certs | cert-manager install
  shell: "helm install cert-manager jetstack/cert-manager --namespace cert-manager --version {{ CERT_MANAGER_VERSION }}"
  when: cert_manager_namespace.rc != 0
  delegate_to: localhost

- name: system | sleep for 60 seconds for cert-manager to get fully set up
  wait_for:
    timeout: 60
  when: cert_manager_namespace.rc != 0
  delegate_to: localhost
