---

# => checks

- name: rancher | prerequisite check | cattle-system namespace
  shell: kubectl get namespaces | grep cattle-system
  changed_when: False
  ignore_errors: yes
  register: cattle_system_namespace
  delegate_to: 127.0.0.1

- name: cert-manager | prerequisite check | cert-manager installed
  shell: kubectl get pods -n cert-manager | grep cert-manager
  changed_when: False
  ignore_errors: yes
  register: cert_manager_installed
  delegate_to: 127.0.0.1

- name: rancher | prerequisite check | rancher installed
  shell: kubectl -n cattle-system rollout status deploy/rancher | grep successfully
  changed_when: False
  ignore_errors: yes
  register: rancher_installed
  delegate_to: 127.0.0.1

# => prerequisites

- name: rancher | add rancher helm repo
  shell: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable && helm repo update
  changed_when: False
  delegate_to: 127.0.0.1

- name: rancher | create cattle-system namespace
  command: kubectl create namespace cattle-system
  when: cattle_system_namespace.rc != 0
  delegate_to: 127.0.0.1

# => install and configure cert-manager

- import_tasks: cert-manager.yml
  when: cert_manager_installed.rc != 0

# => install and configure rancher

- import_tasks: rancher.yml
  when: rancher_installed.rc != 0
